# Generated by Django 4.2.7 on 2024-07-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0024_tournament_pool_play_games_completed_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='primary_position',
            field=models.CharField(choices=[('OFFENSE', 'OFFENSE'), ('DEFENSE', 'DEFENSE'), ('BENCH', 'BENCH')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='d_line_cutters',
            field=models.ManyToManyField(related_name='d_line_cutters_teams', to='frisbee_simulator_web.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='d_line_handlers',
            field=models.ManyToManyField(related_name='d_line_handlers_teams', to='frisbee_simulator_web.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='d_line_hybrids',
            field=models.ManyToManyField(related_name='d_line_hybrids_teams', to='frisbee_simulator_web.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='o_line_cutters',
            field=models.ManyToManyField(related_name='o_line_cutters_teams', to='frisbee_simulator_web.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='o_line_handlers',
            field=models.ManyToManyField(related_name='o_line_handlers_teams', to='frisbee_simulator_web.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='o_line_hybrids',
            field=models.ManyToManyField(related_name='o_line_hybrids_teams', to='frisbee_simulator_web.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Pool Play', 'Pool Play'), ('Pre-Quarterfinal', 'Pre-Quarterfinal'), ('Quarterfinal', 'Quarterfinal'), ('Semifinal', 'Semifinal'), ('Championship', 'Championship'), ('3rd-Place Final', '3rd-Place Final'), ('5th-Place Semifinal', '5th-Place Semifinal'), ('5th-Place Final', '5th-Place Final'), ('7th-Place Final', '7th-Place Final'), ('9th-Place Quarterfinal', '9th-Place Quarterfinal'), ('9th-Place Semifinal', '9th-Place Semifinal'), ('9th-Place Final', '9th-Place Final'), ('11th-Place Final', '11th-Place Final'), ('13th-Place Semifinal', '13th-Place Semifinal'), ('13th-Place Final', '13th-Place Final'), ('15th-Place Final', '15th-Place Final'), ('17th-Place Semifinal', '17th-Place Semifinal'), ('17th-Place Final', '17th-Place Final'), ('19th-Place Final', '19th-Place Final'), ('Exhibition', 'Exhibition')], default='Exhibition', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_teams',
            field=models.PositiveIntegerField(choices=[(4, '4'), (8, '8'), (16, '16'), (20, '20')], default=4),
        ),
    ]
