# Generated by Django 4.2.7 on 2025-07-12 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0025_player_primary_position_team_d_line_cutters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertournamentstat',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_tournament_stats', to='frisbee_simulator_web.team'),
        ),
    ]
