# Generated by Django 4.2.7 on 2025-07-14 17:28

from django.db import migrations


def create_test_objects(apps, schema_editor):
    UFADivision = apps.get_model('frisbee_simulator_web', 'UFADivision')
    UFATeam = apps.get_model('frisbee_simulator_web', 'UFATeam')
    UFAPlayer = apps.get_model('frisbee_simulator_web', 'UFAPlayer')
    UFAPlayerTeam = apps.get_model('frisbee_simulator_web', 'UFAPlayerTeam')
    UFAGame = apps.get_model('frisbee_simulator_web', 'UFAGame')
    UFAPlayerStatsYear = apps.get_model('frisbee_simulator_web', 'UFAPlayerStatsYear')
    Player = apps.get_model('frisbee_simulator_web', 'Player')
    Team = apps.get_model('frisbee_simulator_web', 'Team')

    # Create Division
    division = UFADivision.objects.create(ufa_id=1, name="Atlantic")

    # Create Team
    team = UFATeam.objects.create(
        ufa_id=1,
        year=2024,
        division=division,
        city="Testville",
        name="Testers",
        full_name="Testville Testers",
        abbreviation="TST",
        wins=0, losses=0, ties=0, standing=1
    )

    # Create Player
    ufa_player = UFAPlayer.objects.create(ufa_id=1, first_name="John", last_name="Doe")

    # Link Player to Team
    UFAPlayerTeam.objects.create(
        team=team,
        player=ufa_player,
        active=True,
        year=2024,
        jersey_number=42
    )

    # Create Game
    UFAGame.objects.create(
        ufa_id=1,
        away_team=team,
        home_team=team,
        away_score=0,
        home_score=0,
        status="Scheduled",
        start_timestamp="2024-07-14T12:00:00Z",
        start_timezone="UTC",
        streaming_url="https://testgame.com",
        update_timestamp="2024-07-14T12:00:00Z",
        week=1
    )

    UFAPlayerStatsYear.objects.create(
        player=ufa_player,
        year=2024,
        assists=10, goals=10, hockey_assists=5,
        completions=100, throw_attempts=110, throwaways=5, stalls=0,
        callahans_thrown=0, yards_received=800, yards_thrown=900,
        hucks_attempted=10, hucks_completed=9, catches=100, drops=2,
        blocks=5, callahans_caught=1, pulls=0, recorded_pulls=0,
        ob_pulls=0, recorded_pulls_hangtime=0.0,
        o_points_played=50, o_points_scored=45,
        d_points_played=30, d_points_scored=15,
        seconds_played=3600,
        o_opportunities=60, o_opportunity_scores=50,
        d_opportunities=40, d_opportunity_stops=20
    )


class Migration(migrations.Migration):
    dependencies = [
        ('frisbee_simulator_web', '0027_ufadivision_ufagame_ufaplayer_and_more'),
    ]

    operations = [
        migrations.RunPython(create_test_objects, reverse_code=migrations.RunPython.noop)
    ]
