# Generated by Django 4.2.7 on 2025-07-14 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0028_auto_20250714_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='ufateam',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
