# Generated by Django 4.2.7 on 2025-07-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0029_player_year_team_year_alter_ufateam_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UFAPlayerStatsGame',
        ),
    ]
