# Generated by Django 4.2.7 on 2025-07-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0030_delete_ufaplayerstatsgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bench_cutters',
            field=models.ManyToManyField(blank=True, related_name='bench_cutters_teams', to='frisbee_simulator_web.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='bench_handlers',
            field=models.ManyToManyField(blank=True, related_name='bench_handlers_teams', to='frisbee_simulator_web.player'),
        ),
    ]
