# Generated by Django 4.2.7 on 2025-07-14 21:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0031_team_bench_cutters_team_bench_handlers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UFASeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('number_of_teams', models.PositiveIntegerField(default=24)),
                ('simulation_type', models.CharField(choices=[('player_rating', 'player_rating'), ('team_rating', 'team_rating')], default='player_rating')),
                ('is_complete', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('champion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.team')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.profile')),
                ('teams', models.ManyToManyField(related_name='teams_season', to='frisbee_simulator_web.team')),
            ],
        ),
        migrations.CreateModel(
            name='UFASeasonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_season_wins', models.PositiveIntegerField(default=0)),
                ('regular_season_losses', models.PositiveIntegerField(default=0)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.ufadivision')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.ufaseason')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.team')),
            ],
        ),
    ]
