# Generated by Django 4.2.7 on 2025-07-14 21:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0032_ufaseason_ufaseasonteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='UFASeasonGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('game_type', models.CharField(choices=[('Exhibition', 'Exhibition'), ('Regular Season', 'Regular Season')], default='Exhibition', max_length=50)),
                ('winner_score', models.PositiveIntegerField(default=0)),
                ('loser_score', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.profile')),
                ('loser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser_games', to='frisbee_simulator_web.ufaseasonteam')),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one_games', to='frisbee_simulator_web.ufaseasonteam')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two_games', to='frisbee_simulator_web.ufaseasonteam')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_games', to='frisbee_simulator_web.ufaseasonteam')),
            ],
        ),
        migrations.CreateModel(
            name='UFAPlayerSeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('swing_passes_thrown', models.PositiveIntegerField(default=0)),
                ('swing_passes_completed', models.PositiveIntegerField(default=0)),
                ('under_passes_thrown', models.PositiveIntegerField(default=0)),
                ('under_passes_completed', models.PositiveIntegerField(default=0)),
                ('short_hucks_thrown', models.PositiveIntegerField(default=0)),
                ('short_hucks_completed', models.PositiveIntegerField(default=0)),
                ('deep_hucks_thrown', models.PositiveIntegerField(default=0)),
                ('deep_hucks_completed', models.PositiveIntegerField(default=0)),
                ('throwing_yards', models.IntegerField(default=0)),
                ('receiving_yards', models.IntegerField(default=0)),
                ('turnovers_forced', models.PositiveIntegerField(default=0)),
                ('throwaways', models.PositiveIntegerField(default=0)),
                ('drops', models.PositiveIntegerField(default=0)),
                ('callahans', models.PositiveIntegerField(default=0)),
                ('pulls', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufa_season_stats', to='frisbee_simulator_web.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufa_player_stats', to='frisbee_simulator_web.tournament')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ufa_player_season_stats', to='frisbee_simulator_web.team')),
            ],
        ),
        migrations.CreateModel(
            name='UFAPlayerGameStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('swing_passes_thrown', models.PositiveIntegerField(default=0)),
                ('swing_passes_completed', models.PositiveIntegerField(default=0)),
                ('under_passes_thrown', models.PositiveIntegerField(default=0)),
                ('under_passes_completed', models.PositiveIntegerField(default=0)),
                ('short_hucks_thrown', models.PositiveIntegerField(default=0)),
                ('short_hucks_completed', models.PositiveIntegerField(default=0)),
                ('deep_hucks_thrown', models.PositiveIntegerField(default=0)),
                ('deep_hucks_completed', models.PositiveIntegerField(default=0)),
                ('throwing_yards', models.IntegerField(default=0)),
                ('receiving_yards', models.IntegerField(default=0)),
                ('turnovers_forced', models.PositiveIntegerField(default=0)),
                ('throwaways', models.PositiveIntegerField(default=0)),
                ('drops', models.PositiveIntegerField(default=0)),
                ('callahans', models.PositiveIntegerField(default=0)),
                ('pulls', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufa_player_stats', to='frisbee_simulator_web.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufa_game_stats', to='frisbee_simulator_web.player')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ufa_game_stats_for_season', to='frisbee_simulator_web.season')),
            ],
        ),
    ]
