# Generated by Django 4.2.7 on 2025-07-14 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0033_ufaseasongame_ufaplayerseasonstat_ufaplayergamestat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufaseason',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.team'),
        ),
    ]
