# Generated by Django 4.2.7 on 2025-07-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0034_alter_ufaseason_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ufaseasongame',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.ufaseason'),
        ),
    ]
