# Generated by Django 4.2.7 on 2025-07-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0035_ufaseasongame_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='UFAPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_number_in_game', models.PositiveIntegerField(default=0)),
                ('print_statements', models.CharField(max_length=50000, null=True)),
                ('team_one_score_post_point', models.IntegerField(default=0)),
                ('team_two_score_post_point', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufa_game_points', to='frisbee_simulator_web.ufaseasongame')),
                ('loser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ufa_loser_points', to='frisbee_simulator_web.ufaseasonteam')),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufa_team_one_points', to='frisbee_simulator_web.ufaseasonteam')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufa_team_two_points', to='frisbee_simulator_web.ufaseasonteam')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ufa_winner_points', to='frisbee_simulator_web.ufaseasonteam')),
            ],
        ),
    ]
