# Generated by Django 4.2.7 on 2025-07-14 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0037_ufaplayerpointstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufaplayergamestat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufa_player_stats', to='frisbee_simulator_web.ufaseasongame'),
        ),
        migrations.AlterField(
            model_name='ufaplayergamestat',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ufa_game_stats_for_season', to='frisbee_simulator_web.ufaseason'),
        ),
        migrations.AlterField(
            model_name='ufaplayerpointstat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufa_point_stats_for_game', to='frisbee_simulator_web.ufaseasongame'),
        ),
        migrations.AlterField(
            model_name='ufaplayerseasonstat',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufa_player_stats', to='frisbee_simulator_web.ufaseason'),
        ),
    ]
