# Generated by Django 4.2.7 on 2025-07-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0038_alter_ufaplayergamestat_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufaplayerpointstat',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufa_player_stats', to='frisbee_simulator_web.ufapoint'),
        ),
    ]
