# Generated by Django 4.2.7 on 2025-07-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0039_alter_ufaplayerpointstat_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ufa_player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='frisbee_simulator_web.ufaplayer'),
        ),
    ]
