# Generated by Django 4.2.7 on 2025-07-22 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0040_player_ufa_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ufa_team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='frisbee_simulator_web.ufateam'),
        ),
    ]
