from django.urls import path
from .views import *

urlpatterns = [
    path('players/', PlayerListView.as_view(), name='player-list'),
    path('players/create/', PlayerCreateView.as_view(), name='player-create'),
    path('players/<int:pk>/', PlayerDetailView.as_view(), name='player-detail'),
    path('players/<int:pk>/update/', PlayerUpdateView.as_view(), name='player-update'),
    path('teams/', TeamListView.as_view(), name='team-list'),
    path('teams/create/', TeamCreateView.as_view(), name='team-create'),
    path('teams/<int:pk>/', TeamDetailView.as_view(), name='team-detail'),
    path('teams/<int:pk>/update/', TeamUpdateView.as_view(), name='team-update'),
    path('random-team/', RandomTeamView.as_view(), name='random-team'),
    path('public-teams/', TeamListPublicView.as_view(), name='public-team-list'),
    path('games/', GamesListView.as_view(), name='games-list'),
    path('games/create/', CreateIndividualGameView.as_view(), name='create-individual-game'),
    path('games/simulate/<int:game_id>/', SimulateIndividualGameView.as_view(), name='simulate-individual-game'),
    path('tournaments/<int:tournament_id>/player-stats/', ListPlayerTournamentStatsView.as_view(),
         name='list-player-tournament-stats'),
    path('tournaments/<int:tournament_id>/players/<int:player_id>/stats/', DetailPlayerTournamentStatsView.as_view(),
         name='detail-player-tournament-stats'),
    path('tournaments/<int:tournament_id>/player-game-stats/', ListPlayerGameStatsView.as_view(),
         name='list-player-game-stats'),
    path('tournaments/<int:tournament_id>/players/<int:player_id>/game-stats/', DetailPlayerGameStatsView.as_view(),
         name='detail-player-game-stats'),
    path('tournaments/', ListTournamentsView.as_view(), name='list_tournaments'),
    path('create-tournament/', CreateTournamentView.as_view(), name='create_tournament'),
    path('delete-tournament/<int:pk>/', DeleteTournamentView.as_view(), name='delete_tournament'),
    path('simulate-tournament/<int:pk>/', SimulateTournamentView.as_view(), name='simulate_tournament'),
    path('pool-play-overview/<int:pk>/', PoolPlayOverviewView.as_view(), name='pool_play_overview'),
    path('bracket-overview/<int:pk>/', BracketOverviewView.as_view(), name='bracket_overview'),
    path('simulate-game/<int:game_id>/<int:tournament_id>/', SimulateGameView.as_view(), name='simulate_game'),
    path('check-simulation-status/<int:tournament_id>/', CheckSimulationStatusView.as_view(),
         name='check_simulation_status'),
    path('fetch-latest-games-data/<int:tournament_id>/', FetchLatestGamesDataView.as_view(),
         name='fetch_latest_games_data'),
    path('simulate-full-pool-play/<int:tournament_id>/', SimulateFullPoolPlayView.as_view(),
         name='simulate_full_pool_play'),
    path('simulate-prequarterfinal-round/<int:tournament_id>/', SimulatePrequarterfinalRoundView.as_view(),
         name='simulate_prequarterfinal_round'),
    path('simulate-quarterfinal-round/<int:tournament_id>/', SimulateQuarterfinalRoundView.as_view(),
         name='simulate_quarterfinal_round'),
    path('simulate-semifinal-round/<int:tournament_id>/', SimulateSemifinalRoundView.as_view(),
         name='simulate_semifinal_round'),
    path('simulate-final-round/<int:tournament_id>/', SimulateFinalRoundView.as_view(), name='simulate_final_round'),
    path('save-tournament-player-stats/<int:tournament_id>/', SaveTournamentPlayerStatsView.as_view(),
         name='save_tournament_player_stats'),
    path('get-tournament-results/<int:tournament_id>/', GetTournamentResultsView.as_view(),
         name='get_tournament_results'),
    path('register/', CreateUserView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/view/', UserProfileDetailView.as_view(), name='profile_view'),
]
